
services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
    networks:
      - inception_network
    expose:
      - "9000"

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception_network
    expose:
      - "3306"
    # volumes:
    #   - mariadb:/var/lib/mysql/

networks:
  inception_network:
    driver: bridge

